#!/usr/bin/env python
# mise description="Bootstrap venv with upgraded pip and piptools"

from _shared import pip, reqs_dpath


dev_reqs_fpath = reqs_dpath / 'dev.txt'


def main():
    print('Upgrading pip and installing/upgrading pip-tools')
    pip('install', '--quiet', '-U', 'pip', 'pip-tools')


if __name__ == '__main__':
    main()
